import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared';
import Image from 'next/image';

// This file is GENERATED by the cmdocs pipeline from docs.json.
// Do not edit manually — your changes will be overwritten.

export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: (<><Image src="/logo/light-logo-only.svg" alt="Orion" width={24} height={24} className="size-6 dark:hidden" /><Image src="/logo/dark-logo-only.svg" alt="Orion" width={24} height={24} className="size-6 hidden dark:block" />Orion</>),
    },
      githubUrl: 'https://github.com/orion-passman',
  };
}

export const sidebarOptions = {
  collapsible: true,
  defaultOpenLevel: 0,
};

export const showTabs = true;

export const tabMode = 'auto' as const;

export const explicitTabs: Array<{
  title: string;
  description?: string;
  icon?: string;
  url: string;
  urls?: string[];
  unlisted?: boolean;
}> | null = [
  {
    title: 'Architecture',
    description: 'System architecture, security model, and authentication flow',
    icon: 'Box',
    url: '/architecture/overview',
    urls: ['/architecture/overview', '/architecture/security-model', '/architecture/authentication'],
  },
  {
    title: 'Smart Contract',
    description: 'Sui Move contracts, recovery system, and gas sponsorship',
    icon: 'Code',
    url: '/contract/overview',
    urls: ['/contract/overview', '/contract/recovery-module', '/contract/gas-station'],
  },
  {
    title: 'Extension',
    description: 'Browser extension architecture, crypto engine, and integrations',
    icon: 'Puzzle',
    url: '/extension/overview',
    urls: ['/extension/overview', '/extension/background', '/extension/crypto-engine', '/extension/walrus'],
  },
];

export const pageDisplayOptions = {
  toc: { enabled: true, style: 'normal' as const },
  breadcrumb: true,
  lastUpdated: true,
};

export const rootRedirect: string | null = '/architecture/overview';
