// GENERATED by cmdocs pipeline from docs.json — do not edit.

export const seoConfig = {
  siteName: 'Orion Developer Portal',
  siteDescription: 'Documentation for the Orion Password Manager — a zero-knowledge, decentralized credential manager built on Sui.',
  baseUrl: '',
  titleTemplate: '%s — Orion',
  canonical: true,
  robots: 'index, follow',
  ogImage: '',
} as const;
